#%RAML 1.0 Trait

headers:
  x-rms-transaction:
    required: true
    minLength: 36
    maxLength: 36
    type: string
    example: "hdsfhjdh-jxbv8859-sjdf76493-37486bbd"
  x-rms-clientId: 
    required: true
    type: string
    example: "hdsfhjdh-jxbv859-sjdf7643-3746bbd"
  x-rms-clientSecret: 
    required: true
    type: string
    example: "hdsfhjdh-jxbv859-sjdf7643-3746bbd"    